/**
 * Inventory of gear modifier families this parser claims to understand.
 * A family is supported only when its example line is tested.
 * `localityMode` is not the resolved locality. `contextual` and `unknown`
 * stay unresolved until item context proves local or global.
 */
export const GEAR_MODIFIER_FAMILIES = [
  {
    semanticId: "maximum-life",
    syntax: "+N to maximum Life",
    operation: "added",
    unit: "flat",
    localityMode: "global",
    scope: null,
    example: "+100 to maximum Life",
  },
  {
    semanticId: "maximum-energy-shield",
    syntax: "+N to maximum Energy Shield",
    operation: "added",
    unit: "flat",
    localityMode: "contextual",
    scope: null,
    example: "+40 to maximum Energy Shield",
  },
  {
    semanticId: "increased-energy-shield",
    syntax: "N% increased Energy Shield",
    operation: "increased",
    unit: "percent",
    localityMode: "contextual",
    scope: null,
    example: "20% increased Energy Shield",
  },
  {
    semanticId: "fire-resistance",
    syntax: "+N% to Fire Resistance",
    operation: "added",
    unit: "percent",
    localityMode: "global",
    scope: null,
    example: "+30% to Fire Resistance",
  },
  {
    semanticId: "cold-resistance",
    syntax: "+N% to Cold Resistance",
    operation: "added",
    unit: "percent",
    localityMode: "global",
    scope: null,
    example: "+18% to Cold Resistance",
  },
  {
    semanticId: "lightning-resistance",
    syntax: "+N% to Lightning Resistance",
    operation: "added",
    unit: "percent",
    localityMode: "global",
    scope: null,
    example: "+18% to Lightning Resistance",
  },
  {
    semanticId: "chaos-resistance",
    syntax: "+N% to Chaos Resistance",
    operation: "added",
    unit: "percent",
    localityMode: "global",
    scope: null,
    example: "+12% to Chaos Resistance",
  },
  {
    semanticId: "strength",
    syntax: "+N to Strength",
    operation: "added",
    unit: "flat",
    localityMode: "global",
    scope: null,
    example: "+5 to Strength",
  },
  {
    semanticId: "dexterity",
    syntax: "+N to Dexterity",
    operation: "added",
    unit: "flat",
    localityMode: "global",
    scope: null,
    example: "+8 to Dexterity",
  },
  {
    semanticId: "intelligence",
    syntax: "+N to Intelligence",
    operation: "added",
    unit: "flat",
    localityMode: "global",
    scope: null,
    example: "+10 to Intelligence",
  },
  {
    semanticId: "movement-speed",
    syntax: "N% increased Movement Speed",
    operation: "increased",
    unit: "percent",
    localityMode: "global",
    scope: null,
    example: "20% increased Movement Speed",
  },
  {
    semanticId: "attack-speed",
    syntax: "N% increased Attack Speed",
    operation: "increased",
    unit: "percent",
    localityMode: "contextual",
    scope: null,
    example: "12% increased Attack Speed",
  },
  {
    semanticId: "cast-speed",
    syntax: "N% increased Cast Speed",
    operation: "increased",
    unit: "percent",
    localityMode: "global",
    scope: null,
    example: "10% increased Cast Speed",
  },
  {
    semanticId: "critical-hit-chance",
    syntax: "N% increased Critical Hit Chance",
    operation: "increased",
    unit: "percent",
    localityMode: "contextual",
    scope: null,
    example: "25% increased Critical Hit Chance",
  },
  {
    semanticId: "critical-damage-bonus",
    syntax: "+N% to Critical Damage Bonus",
    operation: "added",
    unit: "percent",
    localityMode: "contextual",
    scope: null,
    example: "+15% to Critical Damage Bonus",
  },
  {
    semanticId: "flat-physical-damage",
    syntax: "Adds N to M Physical Damage",
    operation: "added",
    unit: "flat",
    localityMode: "contextual",
    scope: null,
    example: "Adds 10 to 20 Physical Damage",
  },
  {
    semanticId: "flat-fire-damage",
    syntax: "Adds N to M Fire Damage",
    operation: "added",
    unit: "flat",
    localityMode: "contextual",
    scope: null,
    example: "Adds 5 to 8 Fire Damage",
  },
  {
    semanticId: "flat-cold-damage",
    syntax: "Adds N to M Cold Damage",
    operation: "added",
    unit: "flat",
    localityMode: "contextual",
    scope: null,
    example: "Adds 3 to 6 Cold Damage",
  },
  {
    semanticId: "flat-lightning-damage",
    syntax: "Adds N to M Lightning Damage",
    operation: "added",
    unit: "flat",
    localityMode: "contextual",
    scope: null,
    example: "Adds 1 to 12 Lightning Damage",
  },
  {
    semanticId: "flat-fire-damage-to-attacks",
    syntax: "Adds N to M Fire Damage to Attacks",
    operation: "added",
    unit: "flat",
    localityMode: "global",
    scope: "attacks",
    example: "Adds 10 to 20 Fire Damage to Attacks",
  },
  {
    semanticId: "increased-physical-damage",
    syntax: "N% increased Physical Damage",
    operation: "increased",
    unit: "percent",
    localityMode: "contextual",
    scope: null,
    example: "40% increased Physical Damage",
  },
  {
    semanticId: "increased-elemental-damage",
    syntax: "N% increased Elemental Damage",
    operation: "increased",
    unit: "percent",
    localityMode: "unknown",
    scope: null,
    example: "15% increased Elemental Damage",
  },
  {
    semanticId: "increased-elemental-damage",
    syntax: "N% increased Elemental Damage with Attacks",
    operation: "increased",
    unit: "percent",
    localityMode: "global",
    scope: "attacks",
    example: "80% increased Elemental Damage with Attacks",
  },
  {
    semanticId: "increased-elemental-damage",
    syntax: "N% increased Elemental Damage with Spells",
    operation: "increased",
    unit: "percent",
    localityMode: "global",
    scope: "spells",
    example: "25% increased Elemental Damage with Spells",
  },
  {
    semanticId: "increased-projectile-damage",
    syntax: "N% increased Projectile Damage",
    operation: "increased",
    unit: "percent",
    localityMode: "global",
    scope: "projectile",
    example: "22% increased Projectile Damage",
  },
  {
    semanticId: "projectile-skill-level",
    syntax: "+N to Level of all Projectile Skills",
    operation: "added",
    unit: "flat",
    localityMode: "global",
    scope: "projectile",
    example: "+2 to Level of all Projectile Skills",
  },
  {
    semanticId: "spirit",
    syntax: "+N to Spirit",
    operation: "added",
    unit: "flat",
    localityMode: "global",
    scope: null,
    example: "+15 to Spirit",
  },
  {
    semanticId: "accuracy",
    syntax: "+N to Accuracy Rating",
    operation: "added",
    unit: "flat",
    localityMode: "contextual",
    scope: null,
    example: "+80 to Accuracy Rating",
  },
  {
    semanticId: "armour",
    syntax: "+N to Armour",
    operation: "added",
    unit: "flat",
    localityMode: "unknown",
    scope: null,
    example: "+40 to Armour",
  },
  {
    semanticId: "increased-armour",
    syntax: "N% increased Armour",
    operation: "increased",
    unit: "percent",
    localityMode: "unknown",
    scope: null,
    example: "120% increased Armour",
  },
  {
    semanticId: "evasion",
    syntax: "+N to Evasion Rating",
    operation: "added",
    unit: "flat",
    localityMode: "unknown",
    scope: null,
    example: "+60 to Evasion Rating",
  },
  {
    semanticId: "deflection",
    syntax: "+N to Deflection Rating",
    operation: "added",
    unit: "flat",
    localityMode: "unknown",
    scope: null,
    example: "+25 to Deflection Rating",
  },
] as const;

export type GearSemanticId =
  (typeof GEAR_MODIFIER_FAMILIES)[number]["semanticId"];

export type GearOperation = "added" | "increased" | "reduced";

export type GearUnit = "flat" | "percent";

export type GearLocality = "local" | "global" | "unknown";
